import { api } from './api';
import type { 
  AskQuestionRequest, 
  Question, 
  QuestionHistoryResponse 
} from '@/types';

const DEMO_MODE = true;

const generateMockAnswer = (questionText: string) => ({
  answer: `This is a demo answer for: "${questionText}"\n\nIn a real deployment, this would be generated by the AI using the 4-layer verification pipeline (Generator → Validator → Auditor → Scorer).\n\n**Key Points:**\n1. This is a demonstration of the UI\n2. The actual AI integration requires API keys (Gemini/Groq)\n3. Database connection is needed for persistent storage`,
  confidence: 0.92,
  key_points: [
    'Point 1: Demo mode active',
    'Point 2: Configure AI API keys for real answers',
    'Point 3: Connect PostgreSQL database for persistence',
  ],
  referenced_concepts: ['Demo Concept A', 'Demo Concept B'],
});

const MOCK_VERIFICATION = {
  layer1_generator: {
    passed: true,
    confidence: 0.92,
    answer: 'Demo generated answer',
  },
  layer2_validator: {
    passed: true,
    alignment_score: 85,
    missing_keywords: [],
    irrelevant_points: [],
  },
  layer3_auditor: {
    passed: true,
    logical_errors: [],
    severity: 'none',
  },
  layer4_scorer: {
    passed: true,
    cbse_score: 88,
    marking_feedback: 'Good answer structure for CBSE standards',
  },
  retry_count: 0,
  total_time_ms: 2500,
};

export const questionsService = {
  async askQuestion(data: AskQuestionRequest): Promise<Question> {
    if (DEMO_MODE) {
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      return {
        id: `demo-q-${Date.now()}`,
        user_id: 'demo-user-1',
        subject_id: data.subject_id,
        chapter_id: data.chapter_id,
        question_text: data.question_text,
        answer: generateMockAnswer(data.question_text),
        verification: MOCK_VERIFICATION,
        created_at: new Date().toISOString(),
      };
    }
    
    const response = await api.post<Question>('/questions/ask', data);
    return response.data;
  },

  async getQuestionHistory(limit = 20, offset = 0): Promise<QuestionHistoryResponse> {
    if (DEMO_MODE) {
      await new Promise(resolve => setTimeout(resolve, 300));
      return {
        questions: [],
        total: 0,
        limit,
        offset,
      };
    }
    
    const response = await api.get<QuestionHistoryResponse>('/questions/history', {
      params: { limit, offset },
    });
    return response.data;
  },

  async getQuestion(questionId: string): Promise<Question> {
    if (DEMO_MODE) {
      await new Promise(resolve => setTimeout(resolve, 300));
      throw new Error('Question not found in demo mode');
    }
    
    const response = await api.get<Question>(`/questions/${questionId}`);
    return response.data;
  },
};
