import { api } from './api';
import type { 
  AskQuestionRequest, 
  Question, 
  QuestionHistoryResponse 
} from '@/types';

const DEMO_MODE = true;

const generateMockAnswer = (questionText: string) => ({
  id: `demo-ans-${Date.now()}`,
  question_id: `demo-q-${Date.now()}`,
  layer1_output: {
    answer: `Demo answer for: "${questionText}"`,
    key_points: ['Demo point 1', 'Demo point 2'],
    referenced_concepts: ['Concept A'],
    confidence: 0.92,
  },
  layer2_output: {
    syllabus_alignment: 'aligned',
    missing_keywords: [],
    irrelevant_points: [],
    alignment_score: 85,
  },
  layer3_output: {
    logical_errors: [],
    severity: 'none' as const,
  },
  layer4_output: {
    predicted_score: 8,
    max_marks: 10,
    score_percentage: 80,
    missing_components: [],
  },
  final_answer: `This is a demo answer for: "${questionText}"\n\nIn a real deployment, this would be generated by the AI using the 4-layer verification pipeline.\n\n**Key Points:**\n1. This is a demonstration\n2. Configure AI API keys for real answers\n3. Database connection needed for persistence`,
  confidence_score: 0.92,
  referenced_concepts: ['Demo Concept A', 'Demo Concept B'],
  retries: 0,
  processing_time_ms: 2500,
  status: 'completed',
  created_at: new Date().toISOString(),
});

export const questionsService = {
  async askQuestion(data: AskQuestionRequest): Promise<Question> {
    if (DEMO_MODE) {
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      return {
        id: `demo-q-${Date.now()}`,
        user_id: 'demo-user-1',
        subject_id: data.subject_id,
        chapter_id: data.chapter_id || null,
        question_text: data.question_text,
        answer: generateMockAnswer(data.question_text),
        subject: null,
        chapter: null,
        created_at: new Date().toISOString(),
      };
    }
    
    const response = await api.post<Question>('/questions/ask', data);
    return response.data;
  },

  async getQuestionHistory(limit = 20, offset = 0): Promise<QuestionHistoryResponse> {
    if (DEMO_MODE) {
      await new Promise(resolve => setTimeout(resolve, 300));
      return {
        questions: [],
        total: 0,
      };
    }
    
    const response = await api.get<QuestionHistoryResponse>('/questions/history', {
      params: { limit, offset },
    });
    return response.data;
  },

  async getQuestion(questionId: string): Promise<Question> {
    if (DEMO_MODE) {
      await new Promise(resolve => setTimeout(resolve, 300));
      throw new Error('Question not found in demo mode');
    }
    
    const response = await api.get<Question>(`/questions/${questionId}`);
    return response.data;
  },
};
